---
functional:
  - Возможность искать товары по ключевому слову или категории.
  - Возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Возможность просматривать товары и просматривать подробную информацию о товаре.
  - Возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Возможность просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом.
  - Возможность удалить товар из корзины
  - Возможность оформить заказ с переходом на страницу оплаты.
  - Возможность проветить наличие товаров.
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть доступен на различных устройствах.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен иметь мобильную версию.
  - Магазин — это SPA приложение, которое не перезагружает страницу.
  - Возможность изменить язык приложения на русский.
  - Возможность работать с магазином в браузере Chrome.
  - Возможность работать с магазином в браузере Firefox.
  - Возможность работать с магазином в браузере Opera.
  - Возможность работать с магазином с мобтльного устройства. 
implicit:
  - Возможность изменить язык приложения на  немецкий.
